[tox]
envlist =
;    py39
    py310
    py311
    py312
    py313
    py314
    py315
isolated_build = True
requires =
    tox-uv>=1.28

[testenv]
;extras =
;    fast
deps =
    pytest>=8.0.0
    hypothesis>=6.151.9
    textual>=1.0.0
    pyenchant>=3.2.0
    pytest-xdist>=3.5.0
commands =
    pytest tests/ -v -n 8 -q
