10 REM Insert a formal letter header with date and address placeholders
20 PRINT "                                   [Your Name]"
30 PRINT "                                   [Street Address]"
40 PRINT "                                   [City, State  ZIP]"
50 PRINT ""
60 PRINT "[Date]"
70 PRINT ""
80 PRINT "[Recipient Name]"
90 PRINT "[Title]"
100 PRINT "[Organization]"
110 PRINT "[Street Address]"
120 PRINT "[City, State  ZIP]"
130 PRINT ""
140 PRINT "Dear [Recipient]:"
150 PRINT ""
