10 REM Insert a formatted header from the current Fediverse post
20 PRINT "--- "; PAUTHOR$; " ("; PHANDLE$; ") ---"
30 PRINT "Posted: "; PDATE$
40 IF LEN(PTAGS$) > 0 THEN PRINT "Tags:   "; PTAGS$
50 PRINT ""
60 IF LEN(PLINE1$) > 0 THEN PRINT PLINE1$
70 IF LEN(PLINE2$) > 0 THEN PRINT PLINE2$
80 IF LEN(PLINE3$) > 0 THEN PRINT PLINE3$
90 IF LEN(PLINE4$) > 0 THEN PRINT PLINE4$
100 IF LEN(PLINE5$) > 0 THEN PRINT PLINE5$
