---
name: Create Draft Release
concurrency: changelog
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Python 3.12
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with: {python-version: '3.12'}
      - name: Set up uv
        uses: hynek/setup-cached-uv@4300ec2180bc77d705e626a34e381b81a4772c51  # v2.5.0
      - name: Sync dependencies
        run: uv sync --group dev
      - name: Creating Draft release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: uv run changelogmanager github-release --repository ${{ github.repository }}
